import = [
    "$XDG_CONFIG_HOME/alacritty/themes/themes/palenight.toml"
]

[font]
    size = 9.0
    normal.family = "FiraMono Nerd Font"

[colors]
    primary.background = '0x303030'

[env]
    TERM = "xterm-256color"
