#!/usr/bin/env sh

src_path="$1"
patch_list="$2"
patch_log="$3"

for patch_file in ${patch_list}; do 
    echo "applied: '${patch_file}'" >> "${patch_log}"
    patch -d "${src_path}" < "${patch_file}"
done

# end of file
