#
# .cshrc - csh resource script, read at beginning of execution by each shell
#
# see also csh(1), environ(7).
# more examples available at /usr/share/examples/csh/
#

alias h		history 25
alias j		jobs -l
alias ls	ls -FG
alias la	ls -aF
alias lf	ls -FA
alias ll	ls -lAF

# I cant spell- owo
alias blajah	blahaj


if ($?prompt) then
	# configure gpg-agent terminal for each terminal
	setenv GPG_TTY `tty`

	# An interactive shell -- set some stuff up
	set prompt = "%N@%m:%c %# " # default prompt pre-precmd
	set promptchars = "%#"

	set histfile = ${XDG_CACHE_HOME}/csh.history
	set history = 1000
	set savehist = (1000 merge)

	# save history after every command
	#alias precmd 	'history -M; history -c; history -L'
	#alias postcmd 	'history -S'

	# tmux doesn't set pane_path for some reason? this is a work around c:
	# update prompt in precmd to show git branch.
	# wow this is a mess owo
	alias __git_current_branch 'git rev-parse --abbrev-ref HEAD >& /dev/null && echo "(`git rev-parse --abbrev-ref HEAD`)"'
	alias precmd	'test $?TMUX -eq 1 && tmux set -p @tcsh_pane_path "$PWD";set prompt = "%N@%m`__git_current_branch`:%c %# "'

	set autolist = ambiguous
	# Use history to aid expansion
	set autoexpand
	set autorehash
	set mail = (/var/mail/$USER)
	if ( $?tcsh ) then
		bindkey "^W" backward-delete-word
		bindkey -k up history-search-backward
		bindkey -k down history-search-forward
	endif

endif

# vim: noet
