

# Directories to use
export CONFIG="$XDG_CONFIG_HOME/zsh"

# Plugins
source $CONFIG/oh-my-zsh/plugins.zsh

# Themes
#source $CONFIG/theme/lukerandall.zsh

# Package Manager (oh-my-zsh)
export ZSH="$XDG_CONFIG_HOME/oh-my-zsh"
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/.zcompdump-$HOST"
source $ZSH/oh-my-zsh.sh

# General settings (and overides)
source $CONFIG/modules/prompt.zsh
source $CONFIG/modules/auto-complete.zsh
source $CONFIG/modules/tab-complete-no-expand.zsh
source $CONFIG/modules/aliases.zsh
source $CONFIG/modules/history.zsh

