
# https://github.com/sage-etcher/config-files/blob/main/zsh/zshenv
#
# Sage I. Hendricks
# Last modified: Jan 2nd, 2024


PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
LD_LIBRARY_PATH="/usr/local/lib:/usr/lib:/lib:/usr/local/lib64:/usr/lib64:/lib64:/usr/local/lib32:/usr/lib32:/lib32"
EDITOR="nvim"
PAGER="less"

export PATH LD_LIBRARY_PATH EDITOR PAGER


# end of file
