
# https://github.com/sage-etcher/config-files/blob/main/zsh/zshrc
#
# Sage I. Hendricks
# Last modified: Jan 2nd, 2024


ZSH_CONFIG="$XDG_CONFIG_HOME/zsh"

source "$ZSH_CONFIG/general/completion.zsh"
source "$ZSH_CONFIG/general/history.zsh"
source "$ZSH_CONFIG/general/prompt.zsh"
source "$ZSH_CONFIG/general/zkbd.zsh"
source "$ZSH_CONFIG/general/rebind.zsh"
source "$ZSH_CONFIG/general/alias.zsh"
source "$ZSH_CONFIG/general/constants.zsh"

source "$ZSH_CONFIG/zplug/init.zsh"

source "$ZSH_CONFIG/plug-config/zsh-vi-mode.zsh"


# end of file
